# Generated by Django 3.2.7 on 2024-05-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20211022_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='Изображение'),
        ),
    ]
